import type { WorkspaceTemplate } from "../compose/types";
import type { MorphContext } from "../context/types";
import type { DecisionSpec } from "../decisions/spec";
import type { Facts } from "../facts/types";
import { type Rule, RulesProvider } from "../providers/rules";
import { CapabilityRegistry } from "../registry/registry";
import type { TreeNode } from "../resolver/tree";
export declare const registry: CapabilityRegistry;
export declare const tree: TreeNode;
export declare const templates: WorkspaceTemplate[];
export declare const specs: DecisionSpec[];
export declare const rules: Record<string, Rule>;
export declare const rulesProvider: () => RulesProvider;
export declare const facts: Facts;
export declare function makeCtx(intent: string, over?: Partial<MorphContext>): MorphContext;
